=== rmonico/maestro/maestro-core/dbunit/maestro.dtd
<!ELEMENT dataset (metainf*, task*, tag*, attribute*, property*, tasktag*)>

<!ELEMENT metainf (#PCDATA)>
<!ATTLIST metainf id CDATA #REQUIRED>
<!ATTLIST metainf key CDATA #REQUIRED>
<!ATTLIST metainf value CDATA #REQUIRED>

<!ELEMENT task (#PCDATA)>
<!ATTLIST task id CDATA #REQUIRED>
<!ATTLIST task name CDATA #REQUIRED>
<!ATTLIST task supertask_id CDATA #REQUIRED>

<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag id CDATA #REQUIRED>
<!ATTLIST tag name CDATA #REQUIRED>

<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute id CDATA #REQUIRED>
<!ATTLIST attribute name CDATA #REQUIRED>
<!ATTLIST attribute type CDATA #REQUIRED>
<!ATTLIST attribute tag_id CDATA #REQUIRED>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property id CDATA #REQUIRED>
<!ATTLIST property tasktag_id CDATA #REQUIRED>
<!ATTLIST property attribute_id CDATA #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>

<!ELEMENT tasktag (#PCDATA)>
<!ATTLIST tasktag id CDATA #REQUIRED>
<!ATTLIST tasktag task_id CDATA #REQUIRED>
<!ATTLIST tasktag tag_id CDATA #REQUIRED>

=== rmonico/maestro/maestro-cli/dbunit/TaskListTests__should_list_only_tasks_of_selected_tags.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE dataset SYSTEM "dbunit/maestro.dtd">
<dataset>
	<tag id="1" name="important" />
	<tag id="2" name="buy" />

	<task id="1" name="Task which should not be listed on this test" />
	<task id="2" name="Something important" />
	<task id="3" name="Something import to buy" />
	<task id="4" name="Something not import to buy" />

	<tasktag id="1" task_id="2" tag_id="1" />
	<tasktag id="2" task_id="3" tag_id="1" />
	<tasktag id="3" task_id="3" tag_id="2" />
	<tasktag id="4" task_id="4" tag_id="2" />
</dataset>

=== rmonico/maestro/dbunit/TagRemoveTests__base_data.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE dataset SYSTEM "dbunit/maestro.dtd">
<dataset>
	<tag id="1" name="first_tag" />
	<tag id="2" name="no_attribute_tag" />
	<tag id="3" name="tag_with_attributes" />
	<tag id="4" name="tag_with_tasks" />
	<tag id="5" name="tag_with_tasks_attributes_and_properties" />

	<attribute id="1" name="attr1" type="TEXT" tag_id="3" />
	<attribute id="2" name="another_attribute" type="INTEGER" tag_id="3" />
	<attribute id="3" name="default" type="TEXT" tag_id="5" />
	<attribute id="4" name="creation" type="TEXT" tag_id="5" />

	<task id="1" name="A task" />
	<task id="2" name="Another task" />

	<tasktag id="1" task_id="1" tag_id="4" />
	<tasktag id="2" task_id="2" tag_id="4" />
	<tasktag id="3" task_id="1" tag_id="5" />
	<tasktag id="4" task_id="2" tag_id="5" />
</dataset>

=== rmonico/maestro/maestro-cli/dbunit/TagListTests__should_list_tags_with_task_counts.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE dataset SYSTEM "dbunit/maestro.dtd">
<dataset>
	<tag id="1" name="first_tag" />
	<tag id="2" name="second_tag" />
	<tag id="3" name="third_tag" />
	
	<task id="1" name="Task #1, name will not be used in tests" />
	<task id="2" name="Task #2, name will not be used in tests" />
	<task id="3" name="Task #3, name will not be used in tests" />
	<task id="4" name="Task #4, name will not be used in tests" />
	<task id="5" name="Task #5, name will not be used in tests" />
	<task id="6" name="Task #6, name will not be used in tests" />
	
	<tasktag id="1" task_id="1" tag_id="1" />
	<tasktag id="2" task_id="2" tag_id="1" />
	<tasktag id="3" task_id="1" tag_id="2" />
	<tasktag id="4" task_id="2" tag_id="2" />
	<tasktag id="5" task_id="3" tag_id="2" />
	<tasktag id="6" task_id="4" tag_id="2" />
	<tasktag id="7" task_id="1" tag_id="3" />
	<tasktag id="8" task_id="2" tag_id="3" />
	<tasktag id="9" task_id="3" tag_id="3" />
	<tasktag id="10" task_id="4" tag_id="3" />
	<tasktag id="11" task_id="5" tag_id="3" />
	<tasktag id="12" task_id="6" tag_id="3" />
</dataset>
